Added osu!
techno-tim/littlelink-server pull request #181
Opened 2022-07-19 12:10 UTC by Miko36110

I have 0 coding experience so pls fix the errors, tried my best lol

# Proposed Changes

- added the rhythm game osu!

## Checklist

- [ ] Tested locally `(don't know how to do that)`
- [ ] Ran `yarn ci` to test my code `(don't know how to do that)`
- [x] Did not add any unnecessary changes
- [x] All my changes appear after other changes in each file
- [ ] Included a screenshot (if adding a new button) `(don't know how to test locally so I can't)`
- [ ] 🚀

2022-07-19 12:32 UTC, Choubakawa requested changes
I find some lines that need to be changed but the rest looks good!

2022-07-19 12:32 UTC, Choubakawa commented on src/components/Home/Home.js
> +import tpdbLogo from '../../icons/osu.svg';
Duplicate of `tpdbLogo`, it needs to be named `osuLogo`.

2022-07-19 12:32 UTC, Choubakawa commented on src/components/Home/Home.js
> +                  logo={tpdbLogo}
Have to change `tpdbLogo` to `osuLogo`

2022-07-19 12:44 UTC, Miko36110 commented on src/components/Home/Home.js
> +                  logo={tpdbLogo}
haha thanks!

2022-07-20 15:50 UTC, timothystewart6 commented
Looks like there's some lint, otherwise it's good to go!

run `yarn lint --fix` locally and commit that and push it up!

2022-07-20 22:42 UTC, timothystewart6 commented
Thank you!

2022-07-20 22:42 UTC, merged