feat: Add new buttons
techno-tim/littlelink-server pull request #457
Opened 2023-07-22 19:52 UTC by KieranRobson

# Proposed Changes

- Added Lemmy - Closes #429 
- Added Pixelfed - Closes #407 
- Added VRCHat - Closes #290 
- Remove links for technotim.live due to this now leading to blog rather than link site.

Screenshot (If Applicable)
![image](https://github.com/techno-tim/littlelink-server/assets/32241933/f1212323-fb57-4b57-99ad-298f54d0b523)

## Checklist

- [x] Tested locally
- [x] Ran `yarn ci` to test my code
- [x] Did not add any unnecessary changes
- [x] All my changes appear after other changes in each file
- [x] Included a screenshot (if adding a new button)
- [x] 🚀

2023-07-22 20:10 UTC, Babasile commented
Good catch! Instead of removing you can replace https://technotim.live/ with https://links.technotim.live/

2023-07-23 18:48 UTC, timothystewart6 commented on README.md
> +It takes the same simple approach to a link page and hosts it within a NodeJS server with React Server Side Rendering, containerized for you to use. Now, customizing `LittleLink` with `littlelink-ser
Thanks for noticing!  The new live example is at https://links.technotim.live

2023-07-23 18:48 UTC, timothystewart6 commented on README.md
> -The example below will generate a site exactly like <https://technotim.live>
Thanks for noticing! The new live example is at https://links.technotim.live

2023-07-23 18:49 UTC, timothystewart6 requested changes
A few small tweaks for the links!  Thank you so much!

2023-07-25 13:58 UTC, KieranRobson commented
All done!

2023-07-25 14:22 UTC, timothystewart6 approved these changes

2023-07-25 14:23 UTC, timothystewart6 commented
Thank you!

2023-07-25 14:23 UTC, merged